[versions]

[libraries]
http4k-core = { module = "org.http4k:http4k-core" }
http4k-server-undertow = { module = "org.http4k:http4k-server-undertow" }
http4k-client-apache = { module = "org.http4k:http4k-client-apache" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

[bundles]
